### ISSUE TITLE
Error: Creating accounts through node-steam-user is no longer possible due to Steam changes.

### ISSUE THREAD

**Issue by ishandutta2007** [mprey/steam-account-creator#8]
> /Users/ishandutta2007/Documents/Projects/steam-account-creator/node_modules/steam-user/components/account.js:15
> 	throw new Error("Creating accounts through node-steam-user is no longer possible due to Steam changes.");
> 	^
> 
> Error: Creating accounts through node-steam-user is no longer possible due to Steam changes.
>     at SteamUser.createAccount (/Users/ishandutta2007/Documents/Projects/steam-account-creator/node_modules/steam-user/components/account.js:15:8)
>     at createAccount (/Users/ishandutta2007/Documents/Projects/steam-account-creator/account_creator.js:39:10)
>     at SteamUser.<anonymous> (/Users/ishandutta2007/Documents/Projects/steam-account-creator/account_creator.js:22:3)
>     at emitTwo (events.js:126:13)
>     at SteamUser.emit (events.js:214:7)
>     at SteamUser._handlers.(anonymous function) (/Users/ishandutta2007/Documents/Projects/steam-account-creator/node_modules/steam-user/components/logon.js:310:9)
>     at SteamUser._handleMessage (/Users/ishandutta2007/Documents/Projects/steam-account-creator/node_modules/steam-user/components/messages.js:249:30)
>     at emitThree (events.js:136:13)
>     at CMClient.emit (events.js:217:7)
>     at CMClient._netMsgReceived (/Users/ishandutta2007/Documents/Projects/steam-account-creator/node_modules/steam-client/lib/cm_client.js:323:8)
>

**Comment by ishandutta2007** [comment]
??
